#!/bin/bash

# builds the software for release - should be run using composer.
# this is quick and dirty - hopefully we'll switch to use github actions at some point.

composer install --no-dev --optimize-autoloader

# remove existing file if exists
rm geocore-ce.zip fusion.zip marquee.zip tempo.zip

# add license to base folder and all contents of src to base folder, minus a few things
zip geocore-ce.zip LICENSE
cd src/

# add files in src as the base folder.. but:
# exclude (some are added back partially further down):
#   - config.php
#   - templates_c
#   - user_images
#   - _geocache
#   - geo_templates
#   - .DS_Store files (Mac OS file)
zip ../geocore-ce.zip -r * -x config.php "templates_c/*" "user_images/*" "_geocache/*" "geo_templates/*" "*.DS_Store"

# add the starting files needed for _geocache
zip ../geocore-ce.zip _geocache/index.php _geocache/.htaccess

# Add empty folders for user_images, templates_c
zip ../geocore-ce.zip user_images templates_c

# Add the default template and min.php in geo_templates (Note: we exclude the extra template sets for now)
zip ../geocore-ce.zip geo_templates/min.php -r geo_templates/default/* -x "*.DS_Store"

# Make a download specificaly for the extra template sets - done so they can be uploaded using the manager if desired
cd geo_templates
zip ../../fusion.zip -r fusion -x "*.DS_Store"
zip ../../marquee.zip -r marquee -x "*.DS_Store"
zip ../../tempo.zip -r tempo -x "*.DS_Store"
