<?php

$auctions = array(
            "<<DISPLAY_USERNAME_AUCTIONS>>",
            "<<FEATURED_PIC_LINK_AUCTIONS>>",
            "<<LOGGED_IN_OUT_HTML_10_AUCTIONS>>",
            "<<LOGGED_IN_OUT_HTML_11_AUCTIONS>>",
            "<<LOGGED_IN_OUT_HTML_12_AUCTIONS>>",
            "<<LOGGED_IN_OUT_HTML_13_AUCTIONS>>",
            "<<LOGGED_IN_OUT_HTML_14_AUCTIONS>>",
            "<<LOGGED_IN_OUT_HTML_15_AUCTIONS>>",
            "<<LOGGED_IN_OUT_HTML_16_AUCTIONS>>",
            "<<LOGGED_IN_OUT_HTML_17_AUCTIONS>>",
            "<<LOGGED_IN_OUT_HTML_18_AUCTIONS>>",
            "<<LOGGED_IN_OUT_HTML_19_AUCTIONS>>",
            "<<LOGGED_IN_OUT_HTML_20_AUCTIONS>>",
            "<<LOGGED_IN_OUT_HTML_2_AUCTIONS>>",
            "<<LOGGED_IN_OUT_HTML_3_AUCTIONS>>",
            "<<LOGGED_IN_OUT_HTML_4_AUCTIONS>>",
            "<<LOGGED_IN_OUT_HTML_5_AUCTIONS>>",
            "<<LOGGED_IN_OUT_HTML_6_AUCTIONS>>",
            "<<LOGGED_IN_OUT_HTML_7_AUCTIONS>>",
            "<<LOGGED_IN_OUT_HTML_8_AUCTIONS>>",
            "<<LOGGED_IN_OUT_HTML_9_AUCTIONS>>",
            "<<LOGGED_IN_OUT_HTML_AUCTIONS>>",
            "<<LOGIN_REGISTER_LINK_AUCTIONS>>",
            "<<NEWEST_ADS_LINK_1_AUCTIONS>>",
            "<<NEWEST_ADS_LINK_2_AUCTIONS>>",
            "<<NEWEST_ADS_LINK_3_AUCTIONS>>",
            "<<NEWEST_AUCTIONS_1>>",
            "<<NEWEST_AUCTIONS_2>>",
            "<<NEWEST_AUCTIONS_LINK>>",
            "<CATEGORY_TREE_1_AUCTIONS>",
            "<CATEGORY_TREE_2_AUCTIONS>",
            "<CATEGORY_TREE_3_AUCTIONS>",
            "<CLASSIFIED_NAVIGATION_1_AUCTIONS>",
            "<CLASSIFIED_NAVIGATION_2_AUCTIONS>",
            "<CLASSIFIED_NAVIGATION_3_AUCTIONS>",
            "<FEATURED_AUCTIONS_1>",
            "<FEATURED_AUCTIONS_2>",
            "<FEATURED_AUCTIONS_3>",
            "<FEATURED_AUCTIONS_4>",
            "<FEATURED_AUCTIONS_5>",
            "<FEATURED_CATEGORY_1_AUCTIONS>",
            "<FEATURED_CATEGORY_2_AUCTIONS>",
            "<MAIN_CLASSIFIED_LEVEL_NAVIGATION_1_AUCTIONS>",
            "<MAIN_CLASSIFIED_NAVIGATION_1_AUCTIONS>",
            "<MODULE_FEATURED_1_LEVEL_2_AUCTIONS>",
            "<MODULE_FEATURED_1_LEVEL_3_AUCTIONS>",
            "<MODULE_FEATURED_1_LEVEL_4_AUCTIONS>",
            "<MODULE_FEATURED_1_LEVEL_5_AUCTIONS>",
            "<MODULE_FEATURED_2_LEVEL_2_AUCTIONS>",
            "<MODULE_FEATURED_2_LEVEL_3_AUCTIONS>",
            "<MODULE_FEATURED_2_LEVEL_4_AUCTIONS>",
            "<MODULE_FEATURED_2_LEVEL_5_AUCTIONS>",
            "<MODULE_FEATURED_PIC_1_AUCTIONS>",
            "<MODULE_FEATURED_PIC_1_LEVEL_2_AUCTIONS>",
            "<MODULE_FEATURED_PIC_1_LEVEL_3_AUCTIONS>",
            "<MODULE_FEATURED_PIC_1_LEVEL_4_AUCTIONS>",
            "<MODULE_FEATURED_PIC_1_LEVEL_5_AUCTIONS>",
            "<MODULE_FEATURED_PIC_2_AUCTIONS>",
            "<MODULE_FEATURED_PIC_2_LEVEL_2_AUCTIONS>",
            "<MODULE_FEATURED_PIC_2_LEVEL_3_AUCTIONS>",
            "<MODULE_FEATURED_PIC_2_LEVEL_4_AUCTIONS>",
            "<MODULE_FEATURED_PIC_2_LEVEL_5_AUCTIONS>",
            "<MODULE_FEATURED_PIC_3_AUCTIONS>",
            "<MODULE_HOTTEST_AUCTIONS>",
            "<MODULE_PHP_INSERT_1_AUCTIONS>",
            "<MODULE_PHP_INSERT_2_AUCTIONS>",
            "<MODULE_PHP_INSERT_3_AUCTIONS>",
            "<MODULE_PHP_INSERT_4_AUCTIONS>",
            "<MODULE_PHP_INSERT_5_AUCTIONS>",
            "<MODULE_PHP_INSERT_6_AUCTIONS>",
            "<MODULE_SEARCH_BOX_1_AUCTIONS>",
            "<MODULE_STATE_FILTER_1_AUCTIONS>",
            "<MODULE_ZIP_FILTER_1_AUCTIONS>",
            "<SEARCH_LINK_AUCTIONS>",
            "<<PREVIOUS_AUCTION_LINK>>",
            "<<NEXT_AUCTION_LINK>>",
            "<<AUCTION_ID_LABEL>>",
            "<<AUCTION_ID>>"

        );

        $search = array(    "_AUCTIONS>",   "_AUCTIONS_", "AUCTIONS_",   "AUCTION_ID",    "PREVIOUS_AUCTION_", "NEXT_AUCTION_");
        $replace = array(   ">",            "_ADS_",      "CLASSIFIED_", "CLASSIFIED_ID", "PREVIOUS_AD_",      "NEXT_AD_");

        $userManagement = array(
            "search" => array(
                "PLACE_AUCTION",
                "ACTIVE",
                "EXPIRED",
                "AUCTION_FILTERS",
                "AUCTIONS_SIGNS_AND_FLYERS"
            ),
            "replace" => array(
                "PLACE_AD",
                "ACTIVE_ADS",
                "EXPIRED_ADS",
                "AD_FILTERS",
                "SIGNS_AND_FLYERS"
            )
        );
