{* 16.09.0-79-gb63e5d8 *}

{*
Displays selection of date formats.  To add date format, just add it to the array
that is hard-coded below.

The dropdown field's name should be set in $fieldName and current value 
set in $fieldValue.
*}

{$possibleDateSelections=['M j-G:i',
	'M j-G:i:s',
	'M j-g:i a',
	'M j-g:i:s a',
	'j M-G:i',
	'j M-G:i:s',
	'j M-g:i a',
	'j M-g:i:s a',
	'j/n-G:i',
	'j/n-G:i:s',
	'j/n-g:i a',
	'j/n-g:i:s a',
	'n/j-G:i',
	'n/j-G:i:s',
	'n/j-g:i a',
	'n/j-g:i:s a',
	'j M',
	'j/n',
	'j/n G:i',
	'j/n G:i:s',
	'j/n G:i O',
	'j/n G:i:s O',
	'j/n g:i a',
	'j/n g:i:s a',
	'n/j',
	'n/j G:i',
	'n/j G:i:s',
	'n/j G:i O',
	'n/j G:i:s O',
	'n/j g:i a',
	'n/j g:i:s a',
	'n/j/y',
	'n/j/y G:i',
	'n/j/y G:i:s',
	'n/j/y G:i O',
	'n/j/y G:i:s O',
	'n/j/y g:i a',
	'n/j/y g:i:s a',
	'j/n/y',
	'j/n/y G:i',
	'j/n/y G:i:s',
	'j/n/y G:i O',
	'j/n/y G:i:s O',
	'j/n/y g:i a',
	'j/n/y g:i:s a',
	'n j, Y',
	'l, F j, Y',
	'l, F j, Y, G:i',
	'l, F j, Y, G:i:s',
	'l, F j, Y, G:i O',
	'l, F j, Y, G:i:s O',
	'l, F j, Y, g:i a',
	'l, F j, Y, g:i:s a',
	'F j, Y',
	'F j, Y, G:i',
	'F j, Y, G:i:s',
	'F j, Y, G:i O',
	'F j, Y, G:i:s O',
	'F j, Y, g:i a',
	'F j, Y, g:i:s a',
	'M j, Y, g:i:s a',
	'M j',
	'M j G:i',
	'M j G:i:s',
	'M j G:i O',
	'M j G:i:s O',
	'M j g:i a',
	'M j g:i:s a',
	'M j, Y, G:i',
	'M j, Y, G:i:s',
	'M j, Y, G:i O',
	'M j, Y, G:i:s O',
	'M j, Y, g:i a',	
	'M j, Y, g:i:s a',	
	'M j, Y',
	'd.m.Y',
	'd.m.Y H:i',
	'd.m.Y H:i:s',
	'd.m.Y H:i O',
	'd.m.Y H:i:s O',
	'd.m.Y g:i a',
	'd.m.Y g:i:s a',
	'M Y',
	'r',
	'd F Y',
	'd F Y g:i a',
	'd F Y g:i:s a',
	'd F Y G:i',
	'd F Y G:i:s',
	'd F Y g:i a O',
	'd F Y g:i:s a O',
	'd F Y G:i O',
	'd F Y G:i:s O',
	'D, d F Y',
	'D, d F Y, g:i a',
	'D, d F Y, g:i:s a',
	'D, d F Y, G:i',
	'D, d F Y, G:i:s',
	'D, d F Y, g:i a O',
	'D, d F Y, g:i:s a O',
	'D, d F Y, G:i O',
	'D, d F Y, G:i:s O',
	'd M Y',
	'd M Y, g:i a',
	'd M Y, g:i:s a',
	'd M Y, G:i',
	'd M Y, G:i:s',
	'd M Y, g:i a O',
	'd M Y, g:i:s a O',
	'd M Y, G:i O',
	'd M Y, G:i:s O',
	'Y.m.d',
	'Y.m.d, G:i',
	'Y.m.d, G:i:s',
	'Y.m.d, g:i a',
	'Y.m.d, g:i:s a',
	'Y.m.d, G:i O',
	'Y.m.d, G:i:s O',
	'Y.m.d, g:i a O',
	'Y.m.d, g:i:s a O']}

<select name="{$fieldName}" class="form-control col-md-7 col-xs-12">
	{foreach $possibleDateSelections as $format}
		{if !$noTimes||{$format|replace:['r','i']:''}==$format}
			<option value="{$format}"{if $fieldValue==$format} selected="selected"{/if}>{$smarty.now|format_date:$format}</option>
		{/if}
	{/foreach}
</select>