Text[1] = ["connection type", "SIM - This method can be used if cURL is not available on your server. SIM does require the installation of the \"mhash\" \"plugin\" or library installed and working on your server.  Connect to Authorize.net using one of the two methods.  AIM - This method is the most secure of all options but requires that your server have a non-standard PHP \"plugin\" or library installed on your server and configured within PHP. The library necessary is cURL. If you wish to use this method and have the cURL library installed and working properly on your server choose the AIM method."]
Text[2] = ["merchant login", "Merchant login id you were given to use within the ADC Relay Response message sent to the gateway in the live credit card transaction environment."]
Text[3] = ["merchant password", "<b>Only necessary if you are using the AIM method of connection.</b>  Password you use to log into your Merchant Account."]
Text[4] = ["transaction key", "<b>Only necessary if you are using the AIM method of connection.</b>  The gateway rejects all transactions that do not have a transaction key or that include an invalid key. The transaction key can be obtained from your merchant interface at the gateway's website."]
Text[5] = ["currency codes", "Below is a list of currency codes to send to the gateway. This is the currency you accept payments in."]
Text[6] = ["send gateway email to customer", "Choosing \"yes\" will have the gateway send the customer a receipt of the transaction.  You can customize the header and footer of that email in the customer email header and customer email footer sections below."]
Text[7] = ["send gateway email to admin", "Choosing \"yes\" will have the gateway send an email to the admin address set as the site email everytime a transaction is completed. RECOMMENDED \"YES\" AT FIRST TO MAKE SURE THAT YOUR TRANSACTIONS ARE COMPLETED CORRECTLY."]
Text[8] = ["use password in transaction", "Checking this box will make the password be sent for each transaction."]
Text[9] = ["verify peer within transaction", "Only applicable for AIM connections."]
Text[10] = ["User id","UserId of Payment Access User"]
Text[11] = ["Access Key","Your DES Key from DPS"]
Text[12] = ["Mac Key","Your MAC key from DPS"]
Text[13] = ["Email Address","Email Address of admin who will receive Paymentexpress notification emails"]
Text[14] = ["Currency Codes","Possible currencies that Paymentexpress will accept.  Choose the currency you accept payments in from the list below."]

