Text[1] = ["Display Sub Categories","When this is turned on, all sub categories that are one level below a main category are displayed, and link to the corresponding category."]
Text[2] = ["Display Sub Categories","<strong>How this setting is used to display sub categories:</strong><br /><div style=\"border: thin dashed black; margin:2px; padding:5px;\"><u>Main Category</u><br />Category Description - If displayed<br /><strong><em>[BEFORE LIST SETTING]</em></strong><br />[PREFIX SETTING]<u>Sub Category 1</u><br />[SEPERATOR SETTING]<br />[PREFIX SETTING]<u>Sub Category 2</u><br />[SEPERATOR SETTING]<br />[PREFIX SETTING]<u>Sub Category 3</u><br />[AFTER LIST SETTING]</div>"]
Text[3] = ["Display Sub Categories","<strong>How this setting is used to display sub categories:</strong><br /><div style=\"border: thin dashed black; margin:2px; padding:5px;\"><u>Main Category</u><br />Category Description - If displayed<br />[BEFORE LIST SETTING]<br />[PREFIX SETTING]<u>Sub Category 1</u><br />[SEPERATOR SETTING]<br />[PREFIX SETTING]<u>Sub Category 2</u><br />[SEPERATOR SETTING]<br />[PREFIX SETTING]<u>Sub Category 3</u><br /><strong><em>[AFTER LIST SETTING]</em></strong></div>"]
Text[4] = ["Display Sub Categories","<strong>How this setting is used to display sub categories:</strong><br /><div style=\"border: thin dashed black; margin:2px; padding:5px;\"><u>Main Category</u><br />Category Description - If displayed<br />[BEFORE LIST SETTING]<br /><strong><em>[PREFIX SETTING]</em></strong><u>Sub Category 1</u><br />[SEPERATOR SETTING]<br /><strong><em>[PREFIX SETTING]</em></strong><u>Sub Category 2</u><br />[SEPERATOR SETTING]<br /><strong><em>[PREFIX SETTING]</em></strong><u>Sub Category 3</u><br />[AFTER LIST SETTING]</div>"]
Text[5] = ["Display Sub Categories","<strong>How this setting is used to display sub categories:</strong><br /><div style=\"border: thin dashed black; margin:2px; padding:5px;\"><u>Main Category</u><br />Category Description - If displayed<br />[BEFORE LIST SETTING]<br />[PREFIX SETTING]<u>Sub Category 1</u><br /><strong><em>[SEPERATOR SETTING]</em></strong><br />[PREFIX SETTING]<u>Sub Category 2</u><br /><strong><em>[SEPERATOR SETTING]</em></strong><br />[PREFIX SETTING]<u>Sub Category 3</u><br />[AFTER LIST SETTING]</div>"]

Text[6] = ["Admin Note","This <em>note</em> is only a tool to help you keep track of your pages or modules.<br /><strong>Important:</strong> The note will only be viewable in your Administration Menu.  It does not display anywhere on the front side of your site."]
Text[7] = ["Tag Name","Insert this tag into your templates to use this module.  <br />If you edit the template outside the admin panel, <strong>Remember</strong> to go to <strong>Design &gt; Template Sets</strong> and click the button to re-scan template attachments."]
Text[8] = ["Display \"New Listing\" Icon","The icon used is set within the site setup > browsing section.  You choose whether to display the site wide \"New Listing\" icon within this module here.  The site wide time limit rules apply here also."]

