INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Afghani (Afghanistan)', 'AFA', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Algerian Dinar (Algeria)', 'DZD', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Andorran Peseta (Andorra)', 'ADP', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Argentine Peso (Argentina)', 'ARS', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Armenian Dram (Armenia)', 'AMD', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Aruban Guilder (Aruba)', 'AWG', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Australian Dollar (Australia)', 'AUD', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Azberbaijanian Manat (Azerbaijan)', 'AZM', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Bahamian Dollar (Bahamas)', 'BSD', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Bahaini Dinar (Bahrain)', 'BHD', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Baht (Thailand)', 'THB', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Balboa (Panama)', 'PAB', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Barbados Dollar (Barbados)', 'BBD', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Belarussian Ruble (Belarus)', 'BYB', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Belgian Franc (Belgium)', 'BEF', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Belize Dollar (Belize)', 'BZD', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Bermudian Dollar (Bermuda)', 'BMD', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Bolivar (Venezuela)', 'VEB', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Boliviiano (Bolivia)', 'BOB', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Brazilian Real (Brazil)', 'BRL', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Brunei Dollar (Brunei Darussalam)', 'BND', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Bulgarian Lev (Bulgaria)', 'BGN', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Burundi Franc (Burundi)', 'BIF', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Canadian Dollar (Canada)', 'CAD', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Cape Verde Escudo (Cape Verde)', 'CVE', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Cayman Islands Dollar (Cayman Islands)', 'KYD', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Cedi (Ghana)', 'GHC', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'CFA Franc BCEAO (Guinea-Bissau)', 'XOF', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'CFA Franc BEAC (Central African Republic)', 'XAF', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'CFP Franc (New Caledonia)', 'XPF', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Chilean Peso (Chile)', 'CLP', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Colombian Peso (Colombia)', 'COP', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Comoro Franc (Comoros)', 'KMF', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Convertable Marks (Bosnia And Herzegovina)', 'BAM', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Cordoba Oro (Nicaragua)', 'NIO', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Costa Rican Colon (Costa Rica)', 'CRC', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Cuban Peso (Cuba)', 'CUP', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Cyprus Pound (Cyprus)', 'CYP', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Czech Koruna (Czech Republic)', 'CZK', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Dalasi (Gambia)', 'GMD', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Danish Krone (Denmark)', 'DKK', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Denar (The Former Yugoslav Republic Of Macedonia)', 'MKD', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Deutsche Mark (Germany)', 'DEM', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Dirham (United Arab Emirates)', 'AED', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Djibouti Franc (Djibouti)', 'DJF', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Dobra (Sao Tome And Principe)', 'STD', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Dominican Peso (Dominican Republic)', 'DOP', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Dong (Vietnam)', 'VND', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Drachma (Greece)', 'GRD', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'East Caribbean Dollar (Grenada)', 'XCD', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Egyptian Pound (Egypt)', 'EGP', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'El Salvador Colon (El Salvador)', 'SVC', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Ethiopian Birr (Ethiopia)', 'ETB', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Euro (Europe)', 'EUR', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Falkland Islands Pound (Falkland Islands)', 'FKP', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Fiji Dollar (Fiji)', 'FJD', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Forint (Hungary)', 'HUF', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Franc Congolais (The Democratic Republic Of Congo)', 'CDF', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'French Franc (France)', 'FRF', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Gibraltar Pound (Gibraltar)', 'GIP', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Gold', 'XAU', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Gourde (Haiti)', 'HTG', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Guarani (Paraguay)', 'PYG', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Guinea Franc (Guinea)', 'GNF', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Guinea-Bissau Peso (Guinea-Bissau)', 'GWP', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Guyana Dollar (Guyana)', 'GYD', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Hong Kong Dollar (Hong Kong)', 'HKD', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Hryvnia (Ukraine)', 'UAH', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Iceland Krona (Iceland)', 'ISK', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Indian Rupee (India)', 'INR', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Iranian Rial (Islamic Republic Of Iran)', 'IRR', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Iraqi Dinar (Iraq)', 'IQD', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Irish Pound (Ireland)', 'IEP', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Italian Lira (Italy)', 'ITL', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Jamaican Dollar (Jamaica)', 'JMD', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Jordanian Dinar (Jordan)', 'JOD', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Kenyyan Shilling (Kenya)', 'KES', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Kina (Papua New Guinea)', 'PGK', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Kip (Lao People\'s Democratic Republic)', 'LAK', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Kroon (Estonia)', 'EEK', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Kuna (Croatia)', 'HRK', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Kuwaiti Dinar (Kuwait)', 'KWD', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Kwacha (Malawi)', 'MWK', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Kwacha (Zambia)', 'ZMK', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Kwanza Reajustado (Angola)', 'AOR', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Kyat (Myanmar)', 'MMK', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Lari (Georgia)', 'GEL', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Latvian Lats (Latvia)', 'LVL', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Lebanese Pound (Lebanon)', 'LBP', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Lek (Albania)', 'ALL', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Lempira (Honduras)', 'HNL', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Leone (Sierra Leone)', 'SLL', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Leu (Romania)', 'ROL', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Lev (Bulgaria)', 'BGL', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Liberian Dollar (Liberia)', 'LRD', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Libyan Dinar (Libyan Arab Jamahiriya)', 'LYD', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Lilangeni (Swaziland)', 'SZL', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Lithuanian Litas (Lithuania)', 'LTL', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Loti (Lesotho)', 'LSL', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Luxembourg Franc (Luxembourg)', 'LUF', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Malagasy Franc (Madagascar)', 'MGF', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Malaysian Ringgit (Malaysia)', 'MYR', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Maltese Lira (Malta)', 'MTL', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Manat (Turkmenistan)', 'TMM', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Markka (Finland)', 'FIM', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Mauritius Rupee (Mauritius)', 'MUR', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Metical (Mozambique)', 'MZM', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Mexican Peso (Mexico)', 'MXN', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Mexican Unidad de Inversion (Mexico)', 'MXV', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Moldovan Leu (Republic Of Moldova)', 'MDL', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Moroccan Dirham (Morocco)', 'MAD', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Mvdol (Bolivia)', 'BOV', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Naira (Nigeria)', 'NGN', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Nakfa (Eritrea)', 'ERN', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Namibia Dollar (Namibia)', 'NAD', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Nepalese Rupee (Napal)', 'NPR', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Netherlands (Netherlands)', 'ANG', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Netherlands Guilder (Netherlands)', 'NLG', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'New Dinar (Yugoslavia)', 'YUM', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'New Israeli Sheqel (Israel)', 'ILS', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'New Kwanza (Angola)', 'AON', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'New Taiwan Dollar (Province Of China Taiwan)', 'TWD', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'New Zaire (Zaire)', 'ZRN', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'New Zealand Dollar (New Zealand)', 'NZD', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Ngultrum (Bhutan)', 'BTN', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'North Korean Won (Dem. People\'s Repub. Of Korea)', 'KPW', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Norwegian Krone (Norway)', 'NOK', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Nuevo Sol (Peru)', 'PEN', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Ouguiya (Mauritania)', 'MRO', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Pa\'anga (Tonga)', 'TOP', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Pakistan Rupee (Pakistan)', 'PKR', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Palladium', 'XPD', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Pataca (Macau)', 'MOP', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Peso Uruguayo (Uruguay)', 'UYU', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Philippine Peso (Philippines)', 'PHP', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Platinum', 'XPT', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Portuguese Escudo (Portugal)', 'PTE', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Pound Sterling (United Kingdom)', 'GBP', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Pula (Botswana)', 'BWP', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Qatari Rial (Qatar)', 'QAR', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Quetzal (Guatemala)', 'GTQ', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Rand (Financial) (Lesotho)', 'ZAL', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Rand (South Africa)', 'ZAR', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Rial Omani (Oman)', 'OMR', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Riel (Cambodia)', 'KHR', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Rufiyaa (Maldives)', 'MVR', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Rupiah (Indonesia)', 'IDR', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Russian Ruble (Russian Federation)', 'RUB', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Russian Ruble (Russian Federation)', 'RUR', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Rwanda Franc (Rwanda)', 'RWF', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Saudi Riyal (Saudi Arabia)', 'SAR', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Schilling (Austria)', 'ATS', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Seychelles Rupee (Seychelles)', 'SCR', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Silver', 'XAG', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Singapore Dollar (Singapore)', 'SGD', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Slovak Koruna (Slovakia)', 'SKK', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Solomon Islands Dollar (Solomon Islands)', 'SBD', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Som (Kyrgyzstan)', 'KGS', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Somali Shilling (Somalia)', 'SOS', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Spanish Peseta (Spain)', 'ESP', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Sri Lanka Rupee (Sri Lanka)', 'LKR', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'St Helena Pound (St Helena)', 'SHP', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Sucre (Ecuador)', 'ECS', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Sundanese Dinar (Sudan)', 'SDD', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Surinam Guilder (Suriname)', 'SRG', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Swedish Krona (Sweden)', 'SEK', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Swiss Franc (Switzerland)', 'CHF', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Syrian Pound (Syrian Arab Republic)', 'SYP', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Tajik Ruble (Tajikistan)', 'TJR', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Taka (Bangladesh)', 'BDT', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Tala (Samoa)', 'WST', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Tanzanian Shilling (United Republic Of Tanzania)', 'TZS', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Tenge (Kazakhstan)', 'KZT', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Timor Escudo (East Timor)', 'TPE', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Tolar (Slovenia)', 'SIT', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Trinidad and Tobago Dollar (Trinidad And Tobago)', 'TTD', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Tugrik (Mongolia)', 'MNT', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Tunisian Dinar (Tunisia)', 'TND', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Turkish Lira (Turkey)', 'TRL', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Uganda Shilling (Uganda)', 'UGX', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Unidad de Valor Constante (Ecuador)', 'ECV', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Unidades de fomento (Chile)', 'CLF', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'US Dollar (Next day) (United States)', 'USN', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'US Dollar (Same day) (United States)', 'USS', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'US Dollar (United States)', 'USD', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Uzbekistan Sum (Uzbekistan)', 'UZS', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Vatu (Vanuatu)', 'VUV', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Won (Republic Of Korea)', 'KRW', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Yemeni Rial (Yemen)', 'YER', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Yen (Japan)', 'JPY', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Yuan Renminbi (China)', 'CNY', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Zimbabwe Dollar (Zimbabwe)', 'ZWD', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Zloty (Poland)', 'PLN', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Afghanistan - Afghani', 'AFA', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Canada - Canadian Dollar', 'CAD', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'United States - US Dollar', 'USD', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'United Kingdom - Pounds Sterling', 'GBP', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Albania-Lek', 'ALL', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Algeria-Algerian Dinar', 'DZD', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Angola-New Kwanza', 'AON', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Argentina-Argentine Peso', 'ARS', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Aruba-Aruban Guilder', 'AWG', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Australia-Australian Dollar', 'AUD', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Austria-Euro', 'EUR', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Bahamas-Bahamian Dollar', 'BSD', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Bahrain-Bahraini Dinar', 'BHD', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Bangladesh-Taka', 'BDT', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Barbados-Barbados Dollar', 'BBD', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Belgium-Euro', 'EUR', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Belize-Belize Dollar', 'BZD', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Bermuda-Bermudian Dollar', 'BMD', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Bolivia-Boliviano', 'BOB', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Bosnia & Herzegovina-Bosnian Dinar', 'BAD', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Botswana-Pula', 'BWP', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Brazil-Real', 'BRL', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Brunei-Brunei Dollar', 'BND', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Bulgaria-Lev', 'BGL', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Burkina Faso, Mali, Senegal-CFA Franc BCEAO', 'XOF', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Burundi-Burundi Franc', 'BIF', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Cambodia-Cambodia Riel', 'KHR', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Cameroon, Central African Republic, Chad, Congo, E', 'XAF', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Cape Verde-Cape Verde Escudo', 'CVE', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Cayman Islands-Cayman Islands Dollar', 'KYD', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Chile-Chilean Peso', 'CLP', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'China-Yuan Renminbi', 'CNY', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Colombia-Colombian Peso', 'COP', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Comoros-Comoro Franc', 'KMF', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Costa Rica-Costa Rican Colon', 'CRC', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Croatia-Croatian Kuna', 'HRK', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Cuba-Cuban Peso', 'CUP', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Cyprus-Cyprus Pound', 'CYP', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Czech Republic-Czech Koruna', 'CZK', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Denmark-Danish Krone', 'DKK', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Djibouti-Djibouti Franc', 'DJF', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Dominica-East Caribbean Dollar', 'XCD', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Dominican Republic-Dominican Peso', 'DOP', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'East Timor-Timor Escudo', 'TPE', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Ecuador-Ecuador Sucre', 'ECS', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Egypt-Egyptian Pound', 'EGP', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'El Salvador-El Salvador Colon', 'SVC', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Estonia-Kroon', 'EEK', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Ethiopia-Ethiopian Birr', 'ETB', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Europe-Euro', 'EUR', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Falkland Islands-Falkland Islands Pound', 'FKP', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Fiji-Fiji Dollar', 'FJD', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Finland-Euro', 'EUR', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'France-Euro', 'EUR', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'French Polynesia-CFP Franc', 'XPF', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Gambia-Dalasi', 'GMD', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Germany-Euro', 'EUR', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Ghana-Cedi', 'GHC', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Gibraltar-Gibraltar Pound', 'GIP', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Greece-Euro', 'EUR', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Guatemala-Quetzal', 'GTQ', 0, 0);
INSERT INTO geodesic_choices (type_of_choice, display_value, value, numeric_value, display_order)  VALUES ( 75, 'Guinea-Guinea Franc', 'GNF', 0, 0);