<?php
//config.default.php

# DO NOT EDIT THIS FILE!!!  Edit config.php instead!!!!
# DO NOT EDIT THIS FILE!!!  Edit config.php instead!!!!
# DO NOT EDIT THIS FILE!!!  Edit config.php instead!!!!
# DO NOT EDIT THIS FILE!!!  Edit config.php instead!!!!
# DO NOT EDIT THIS FILE!!!  Edit config.php instead!!!!

# If you do not have config.php, rename config.example.php to config.php and edit that.

# If there is a setting in this file you want to change, copy it over to
# config.php and change it there.

$db_host = "your_database_hostname";
$db_username = "your_database_user";
$db_password = "your_database_password";
$database = "your_database_name";

$strict_mode = 1;//Set to 0 if MySQL is NOT in strict mode. If you are not sure, leave it set to 1.

//only used for upgrades
$product_type = 4;
$db_type ='mysql';

//include the main config.php so that it over-writes any of the default settings.
require (dirname(__FILE__).'/config.php');
//some Windows servers have trouble finding the config file if the full path isn't specified
//but if the above doesn't work for some reason, try:
//require('config.php');

if (!defined('GEO_IGNORE_USER_ABORT')) {
	//by default, call ignore_user_abort
	define('GEO_IGNORE_USER_ABORT',true);
}

if (!defined('GEO_CACHE_CONTROL')) {
	//by default, send cache control headers
	define ('GEO_CACHE_CONTROL', true);
}

if (!defined('GEO_TIMEZONE_SET_GUESS')) {
	//by default, call method to get, then set, the time zone to stop a bazillion
	//notices (and a few thrown exceptions in certain areas)
	define ('GEO_TIMEZONE_SET_GUESS',true);
}

//Temporary charset clean setting -must be charset compatible with htmlspecialchars
//See http://www.php.net/htmlspecialchars for compatible charsets to use. This
//is the charset used when cleaning strings, similar to this:
//htmlspecialchars($string, ENT_COMPAT,CHARSET_CLEAN)
if (!defined('CHARSET_CLEAN')) {
	define('CHARSET_CLEAN', ((defined('CHARSET'))? CHARSET: 'UTF-8'));
}

//Optional - Charset from - used to convert a string to a certain charset before
//cleaning it, see http://www.php.net/mb_convert_encoding - this is used BEFORE
//cleaning, similar to this: mb_convert_encoding($string, CHARSET_CLEAN, CHARSET_FROM);
//if set to false or not set, then a string's charset will not be converted
//prior to cleaning it.  Note that this can be set independantly of CHARSET_TO
if (!defined('CHARSET_FROM')) {
	define('CHARSET_FROM',false);
}

//Optional - Charset to - used to convert a string to a certain charset after
//cleaning it, see http://www.php.net/mb_convert_encoding - this is used AFTER
//cleaning, similar to this: mb_convert_encoding($string, CHARSET_TO, CHARSET_CLEAN);
//if set to false or not set, then a string's charset will not be converted
//after cleaning it.  Note that this can be set independantly of CHARSET_FROM
if (!defined('CHARSET_TO')) {
	define('CHARSET_TO',false);
}

//optional, un-comment to use mb_convert_string(), or un-comment and change
//the 'mb_convert_string' to 'iconv' to use iconv()
//instead for string conversions.  Valid settings are 'mb_convert_string'
//and 'iconv'.

if (!defined('CLEAN_METHOD')) {
	define('CLEAN_METHOD', 'mb_convert_string');
}

//set up the default directory locations.
//Do not change these settings here.  If you need to change a directory
//location, copy the setting to your config.php and the software will use that
//setting instead of the one below.

//The base folder for the software.
if (!defined('GEO_BASE_DIR')) {
	$base_path = dirname(__FILE__);
	if (strtoupper(substr(PHP_OS, 0, 3)) === 'WIN') {
		//Windows, convert \ to / in path
		$base_path = str_replace('\\','/',$base_path);
	}
	define ('GEO_BASE_DIR',$base_path.'/');
	unset($base_path);
}

//Old name for geo base dir, define for compatibility
////For COMPATIBILITY ONLY!!!  Do NOT use this constant!!
//Use GEO_BASE_DIR Instead!
if (!defined('BASE_DIR')) {
	define ('BASE_DIR',GEO_BASE_DIR);
}

//The location of your classes directory.
if (!defined('CLASSES_DIR')) {
	define("CLASSES_DIR", GEO_BASE_DIR."classes/");
}

//The location of your modules directory.
if (!defined('MODULES_DIR')) {
	define("MODULES_DIR", GEO_BASE_DIR."modules/");
}

//The location of the print directory.
if (!defined('PRINT_DIR')) {
	define("PRINT_DIR", GEO_BASE_DIR."print/");
}

//The api dir
if (!defined('API_DIR')) {
	define('API_DIR',CLASSES_DIR.'api/');
}

//The location of the cron directory.
if (!defined('CRON_DIR'))
	define('CRON_DIR',CLASSES_DIR.'cron/');

//the location of your admin directory, relative to base_dir.
//NOTE: It is important that this is properly set, or your license validation will fail.
if (!defined('ADMIN_LOCAL_DIR')) {
	define ('ADMIN_LOCAL_DIR', 'admin/');
}

//the absolute location of your admin directory.
if (!defined('ADMIN_DIR')) {
	define ('ADMIN_DIR', GEO_BASE_DIR.ADMIN_LOCAL_DIR);
}


//the absolute location of the addon directory.
if (!defined('ADDON_DIR')) {
	define ('ADDON_DIR',GEO_BASE_DIR.'addons/');
}

//Just an alias for ADDON_DIR
if (!defined('ADDONS_DIR')) {
	define ('ADDONS_DIR',ADDON_DIR);
}

//the local folder name for geo_templates/ - this should NOT be a full URL or it
//will break things.
if (!defined('GEO_TEMPLATE_LOCAL_DIR')) {
	define('GEO_TEMPLATE_LOCAL_DIR', 'geo_templates/');
}

if (!defined('GEO_TEMPLATE_DIR')) {
	define ('GEO_TEMPLATE_DIR',GEO_BASE_DIR . GEO_TEMPLATE_LOCAL_DIR);
}

if (!defined('GEO_JS_LIB_LOCAL_DIR')) {
	define('GEO_JS_LIB_LOCAL_DIR', 'js/');
}

if (!defined('GEO_TEMPLATE_COMPILE_DIR')) {
	define ('GEO_TEMPLATE_COMPILE_DIR',GEO_BASE_DIR . 'templates_c/');
}
//If your server does not properly set the domain name, un-comment the following
//line, and replace the domain name with the proper setting, and move to config.php file
#define ('COOKIE_DOMAIN','.YourClassifiesSite.com');

//If you wish to change the expiration time for cookies, un-comment
//the following line, and change as needed.  The default value is
//3 days, 259200 seconds.  You can also set to 0 to make the cookie
//expire as soon as the user closes their browser.
#define('COOKIE_EXPIRE',259200); //expire after 3 days(259200 seconds)


/*
 ----Cache Settings----
 The cache system is able to use different methods to store the cache, the
 settings below are the controls to how they are stored.
*/

// Cache "storage" method: either "filesystem" or "memcache".  If set to
// "memcache", the system must be configured to use memcache, and the memcache
// extension must be installed for PHP.

if (!defined('GEO_CACHE_STORAGE')) {
	define ('GEO_CACHE_STORAGE','filesystem');
}

/* ---- FILESYSTEM CACHE SPECIFIC SETTINGS ---- */

//the absolute location of the geocache dir
if (!defined('CACHE_DIR')) {
	define ('CACHE_DIR',GEO_BASE_DIR.'_geocache/');
}

/* ---- MEMCACHE CACHE SPECIFIC SETTINGS ---- */
// If you have multiple Geo installations, using the same cache, change this
// prefix to be different for each installation.  Otherwise, leave at default.
if (!defined('GEO_MEMCACHE_SETTING_PREFIX')) {
	define ('GEO_MEMCACHE_SETTING_PREFIX','GEO');
}

if (!defined('GEO_MESSAGES')) {
	define('GEO_SUCCESS',1);
	define('GEO_NOTICE',2);
	define('GEO_FAILURE',3);
	define('GEO_ERROR',3);
	define('GEO_MESSAGES',1);
}
